# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-zub1cg"
BBFILE_PATTERN_meta-zub1cg = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-zub1cg = "6"

LAYERDEPENDS_meta-zub1cg = "core"
LAYERSERIES_COMPAT_meta-zub1cg = "scarthgap"
