# meta-zub1cg - board support for the Avnet ZUBoard 1CG (AES-ZUB-1CG-DK-G)

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "zub1cg"
BBFILE_PATTERN_zub1cg = "^${LAYERDIR}/"
BBFILE_PRIORITY_zub1cg = "10"
LAYERDEPENDS_zub1cg = "core"
LAYERSERIES_COMPAT_zub1cg = "scarthgap"
