# Recreate the Vivado project from committed sources.
#
# The project lives in build/hw/vivado and is disposable: it is deleted
# and rebuilt on every run and never committed. IP Integrator block
# designs are far better supported in project mode, so a scripted,
# throwaway project is used instead of pure non-project mode.

source [file join [file dirname [info script]] common.tcl]

file delete -force $proj_dir
create_project $proj_name $proj_dir -part $part

# --- Board part (board files are not part of this repo) ---------------
if {[llength [get_board_parts -quiet $board_part]] == 0} {
    error "Board part '$board_part' not found. Install the Avnet/Tria ZUBoard\
           board files (Vivado board store or <install>/data/boards), or set\
           BOARD_REPO_PATH to a directory containing them."
}
set_property board_part $board_part [current_project]
set_property target_language Verilog [current_project]

# --- HDL sources -------------------------------------------------------
set hdl [glob -nocomplain -directory [file join $hw_dir rtl] *.v *.sv *.vhd]
if {[llength $hdl]} {
    add_files -norecurse $hdl
}

# --- Standalone IP (optional) -----------------------------------------
foreach f [lsort [glob -nocomplain -directory [file join $hw_dir ip] *.tcl]] {
    puts "INFO: sourcing IP script $f"
    source $f
}
set xci [glob -nocomplain -directory [file join $hw_dir ip] *.xci]
if {[llength $xci]} {
    import_ip $xci
}

# --- Constraints -------------------------------------------------------
set xdc [glob -nocomplain -directory [file join $hw_dir constraints] *.xdc]
if {[llength $xdc]} {
    add_files -fileset constrs_1 -norecurse $xdc
}

# --- Block design ------------------------------------------------------
# The script generated by write_bd_tcl builds the design inside the
# project we just opened and ends with validate_bd_design + save.
source [file join $hw_dir bd ${bd_name}.tcl]

set bd_file [get_files -quiet ${bd_name}.bd]
if {$bd_file eq ""} {
    error "Block design '$bd_name' was not created; check the messages above."
}
generate_target all $bd_file

# --- Top level ---------------------------------------------------------
# The wrapper is committed in hw/rtl so custom logic can be added around
# the BD later. If it is missing, fall back to a generated one.
if {[get_files -quiet ${top}.v] eq ""} {
    puts "WARNING: $top.v not found in hw/rtl; using a generated wrapper."
    make_wrapper -files $bd_file -top
    set gen [glob -nocomplain [file join $proj_dir ${proj_name}.gen sources_1 bd $bd_name hdl ${top}.v]]
    if {$gen eq ""} {
        error "Could not locate the generated wrapper $top.v"
    }
    add_files -norecurse $gen
}
set_property top $top [current_fileset]
update_compile_order -fileset sources_1

puts "INFO: project ready at $proj_file"
close_project
